---
ansible_connection: "httpapi"
ansible_network_os: "restconf"
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_httpapi_port: 9443
ansible_httpapi_restconf_root: "/restconf"
ansible_user: "developer"
ansible_password: "C1sco12345"

new_interface:
  interface:
    - name: "Loopback6969"
      description: "Added with Ansible/RESTCONF!"
      type: "iana-if-type:softwareLoopback"
      enabled: true
      ietf-ip:ipv4:
        address:
          - ip: "10.69.69.1"
            netmask: "255.255.255.255"
...
